---
title: "A Week of ECM"
publish: true
---

#+TITLE: A Week of ECM

After a week of listening pretty much exclusively to American
Football's [[https://open.spotify.com/album/7ki5b310cwDVVJBevBLwdw?si%253DjatKDZjtQgaT45nkJGHNHw][/LP3/]], I recalled seeing in a review of /LP2/ the
mentioning of their musical kinship, or maybe better put, descendance,
from Steve Reich. I pulled up Reich's compilation, /The ECM
Recordings/ and was immediately immersed into /Music For 18 Musicians/
for my walk from the bus to the office.

···

** Monday (It was actually Tuesday)

As I'd mentioned, I started the week with Reich's /Music for 18
Musicians/, and by way of serendipity, I found my brain freed from the
lines of code waiting to be reviewed to be acutely attuned to the
music in my ears right as it reached the 33-minute mark. A
Cabernet-like full body swell fills in the minuscule gaps between the
percussive 16th notes looping over one another and /Music For 18
Musicians/ becomes beautiful all at once.

** Wednesday (where "Wednesday" includes Tuesday night)

Okay, so, a few years ago I learned about Meredith Monk's /Songs of
Ascension/ and about how it was performed. [[https://www.youtube.com/watch?v%3Dc3mSVR3xtfU][Monk and her Vocal Ensemble
occupied the spirals of Ann Hamilton's Tower's staircase]] and literally
ascended the stairs while performing the music of /Songs/. To watch it
is to plot its beauty on all its axes, however, when only listening, one is
left with merely a projection of its intention, an abstraction of its
possibility.

It's funny, now that I've watched the video again, I feel silly
recapitulating my notes from my listening to this earlier this
week. But nevertheless, that *is* why I'm doing this. I found that,
without context, Monk's music is hard to countenance. Her "vocal
explorations" really push the boundary on what I can take
seriously. Unlike [[https://www.youtube.com/watch?v%3D75WFTHpOw8Y][Björk, for instance, who is course not
beyond reproach in terms of seriousness-taking,]] whose foray into vocal
exploration with /Medulla/ is quite palatable, insofar as any other
Björk record is at least. Monk's and Björk's angles are,
quite different, though. Monk is pushing the voice's purpose in a piece
of music while Björk's angle is more paradoxical—her's is to hide it by making it
serve /all/ purposes.

/Mapping/, /Songs/' sixth track, presents with
Monk's whimsical yelps and Xenakis-like percussion. It's moments like
this that this line for me, that of seriousness-taking—which,
obviously, I've up to now been unable to give a proper title—is its
most tenuous. It's a line drawn by our experience with art, by our
/context/, like, well, most anything else, really. When pondering the
effects of this absence of context, I find myself imagining its
opposite, i.e. to have /all/ the context, about everything. Maybe this
is the distinction between a binary omniscience and something more
fluid, say, /enlightenment/. To know all is to never learn again,
the death of creativity. I'd posit that Epicureans would
say that this contextual evolution ought to be our /raison d'être/ but
I think it's more visceral than that; I'd say it how we know we're
alive at all.
